use rocket::get;
use serde::Serialize;

use crate::response::WebResponse;
use crate::result::{IntoResult, Result};

#[derive(Debug, Clone, Serialize)]
pub struct StrategyTemplateParam {
    pub key: String,
    pub label: String,
    pub r#type: String,
    pub required: bool,
    pub default_value: Option<serde_json::Value>,
    pub description: Option<String>,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub options: Option<Vec<serde_json::Value>>,
}

#[derive(Debug, Clone, Serialize)]
pub struct StrategyTemplateDto {
    pub template: String,
    pub label: String,
    pub description: String,
    pub params: Vec<StrategyTemplateParam>,
}

#[get("/api/strategy-templates")]
pub async fn list_strategy_templates_handler() -> Result<WebResponse<Vec<StrategyTemplateDto>>> {
    let templates = vec![
        StrategyTemplateDto {
            template: "price_volume_candlestick".to_string(),
            label: "价量K线策略".to_string(),
            description: "基于价格和成交量的K线形态分析".to_string(),
            params: vec![],
        },
        StrategyTemplateDto {
            template: "bottom_volume_surge".to_string(),
            label: "底部放量上涨策略".to_string(),
            description: "识别底部区域的放量上涨信号".to_string(),
            params: vec![],
        },
        StrategyTemplateDto {
            template: "long_term_bottom_reversal".to_string(),
            label: "长期底部反转策略".to_string(),
            description: "寻找长期底部的反转机会".to_string(),
            params: vec![],
        },
        StrategyTemplateDto {
            template: "yearly_high".to_string(),
            label: "年内新高策略".to_string(),
            description: "筛选创年内新高的强势股".to_string(),
            params: vec![],
        },
        StrategyTemplateDto {
            template: "price_strength".to_string(),
            label: "价格强弱策略".to_string(),
            description: "基于相对强弱指标的选股".to_string(),
            params: vec![],
        },
        StrategyTemplateDto {
            template: "distressed_reversal".to_string(),
            label: "困境反转策略".to_string(),
            description: "寻找困境中的反转机会".to_string(),
            params: vec![],
        },
        StrategyTemplateDto {
            template: "single_limit_up".to_string(),
            label: "单次涨停策略".to_string(),
            description: "识别单次涨停后的机会".to_string(),
            params: vec![],
        },
        StrategyTemplateDto {
            template: "fundamental".to_string(),
            label: "基本面策略".to_string(),
            description: "基于财务指标的价值投资策略".to_string(),
            params: vec![],
        },
        StrategyTemplateDto {
            template: "consecutive_strong".to_string(),
            label: "连续强势股策略".to_string(),
            description: "筛选连续强势表现的股票".to_string(),
            params: vec![],
        },
        StrategyTemplateDto {
            template: "turtle".to_string(),
            label: "海龟交易策略".to_string(),
            description: "经典的趋势跟踪策略".to_string(),
            params: vec![StrategyTemplateParam {
                key: "preset".to_string(),
                label: "预设".to_string(),
                r#type: "string".to_string(),
                required: false,
                default_value: Some(serde_json::json!("system1")),
                description: None,
                min: None,
                max: None,
                options: Some(vec![
                    serde_json::json!("system1"),
                    serde_json::json!("system2"),
                    serde_json::json!("conservative"),
                    serde_json::json!("aggressive"),
                ]),
            }],
        },
        StrategyTemplateDto {
            template: "limit_up_pullback".to_string(),
            label: "涨停回调策略".to_string(),
            description: "涨停后回调的买入机会".to_string(),
            params: vec![StrategyTemplateParam {
                key: "preset".to_string(),
                label: "预设".to_string(),
                r#type: "string".to_string(),
                required: false,
                default_value: Some(serde_json::json!("standard")),
                description: None,
                min: None,
                max: None,
                options: Some(vec![
                    serde_json::json!("standard"),
                    serde_json::json!("aggressive"),
                    serde_json::json!("conservative"),
                    serde_json::json!("strong_stock"),
                ]),
            }],
        },
        StrategyTemplateDto {
            template: "strong_close".to_string(),
            label: "强势收盘策略".to_string(),
            description: "基于收盘强势的选股策略".to_string(),
            params: vec![StrategyTemplateParam {
                key: "preset".to_string(),
                label: "预设".to_string(),
                r#type: "string".to_string(),
                required: false,
                default_value: Some(serde_json::json!("standard")),
                description: None,
                min: None,
                max: None,
                options: Some(vec![
                    serde_json::json!("standard"),
                    serde_json::json!("aggressive"),
                    serde_json::json!("conservative"),
                    serde_json::json!("super_strong"),
                ]),
            }],
        },
        StrategyTemplateDto {
            template: "quality_value".to_string(),
            label: "优质价值策略".to_string(),
            description: "寻找优质且被低估的股票".to_string(),
            params: vec![StrategyTemplateParam {
                key: "preset".to_string(),
                label: "预设".to_string(),
                r#type: "string".to_string(),
                required: false,
                default_value: Some(serde_json::json!("standard")),
                description: None,
                min: None,
                max: None,
                options: Some(vec![
                    serde_json::json!("standard"),
                    serde_json::json!("strict"),
                    serde_json::json!("small_cap_growth"),
                    serde_json::json!("large_cap_blue_chip"),
                ]),
            }],
        },
        StrategyTemplateDto {
            template: "turnover_ma_bullish".to_string(),
            label: "换手率均线多头策略".to_string(),
            description: "基于换手率区间与均线多头排列的选股策略".to_string(),
            params: vec![
                StrategyTemplateParam {
                    key: "min_turnover_rate".to_string(),
                    label: "最小换手率(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(5.0)),
                    description: None,
                    min: Some(0.0),
                    max: Some(100.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "max_turnover_rate".to_string(),
                    label: "最大换手率(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(15.0)),
                    description: None,
                    min: Some(0.0),
                    max: Some(100.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "short_ma_period".to_string(),
                    label: "短期均线周期".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(5)),
                    description: None,
                    min: Some(1.0),
                    max: Some(250.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "medium_ma_period".to_string(),
                    label: "中期均线周期".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(20)),
                    description: None,
                    min: Some(1.0),
                    max: Some(500.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "long_ma_period".to_string(),
                    label: "长期均线周期".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(60)),
                    description: None,
                    min: Some(1.0),
                    max: Some(1000.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "require_price_above_all_ma".to_string(),
                    label: "要求价格在均线之上".to_string(),
                    r#type: "boolean".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(true)),
                    description: None,
                    min: None,
                    max: None,
                    options: None,
                },
                StrategyTemplateParam {
                    key: "min_ma_slope".to_string(),
                    label: "均线向上最小斜率(%)".to_string(),
                    r#type: "number".to_string(),
                    required: false,
                    default_value: Some(serde_json::json!(0.5)),
                    description: None,
                    min: Some(-100.0),
                    max: Some(100.0),
                    options: None,
                },
            ],
        },
        StrategyTemplateDto {
            template: "turnover_rise".to_string(),
            label: "换手率区间涨幅策略".to_string(),
            description: "过去N天每日换手率/涨跌幅在范围内，且区间累计涨幅在范围内".to_string(),
            params: vec![
                StrategyTemplateParam {
                    key: "lookback_days".to_string(),
                    label: "回看天数".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(5)),
                    description: None,
                    min: Some(1.0),
                    max: Some(120.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "pre_lookback_days".to_string(),
                    label: "前置窗口天数".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(3)),
                    description: None,
                    min: Some(0.0),
                    max: Some(120.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "pre_total_rise_min_pct".to_string(),
                    label: "前置窗口累计涨幅最小值(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(3.0)),
                    description: None,
                    min: Some(-100.0),
                    max: Some(200.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "pre_total_rise_max_pct".to_string(),
                    label: "前置窗口累计涨幅最大值(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(5.0)),
                    description: None,
                    min: Some(-100.0),
                    max: Some(200.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "turnover_rate_min".to_string(),
                    label: "换手率最小值(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(3.0)),
                    description: None,
                    min: Some(0.0),
                    max: Some(100.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "turnover_rate_max".to_string(),
                    label: "换手率最大值(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(100.0)),
                    description: None,
                    min: Some(0.0),
                    max: Some(100.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "daily_pct_change_min".to_string(),
                    label: "每日涨跌幅最小值(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(3.0)),
                    description: None,
                    min: Some(-100.0),
                    max: Some(200.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "daily_pct_change_max".to_string(),
                    label: "每日涨跌幅最大值(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(20.0)),
                    description: None,
                    min: Some(-100.0),
                    max: Some(200.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "total_rise_min_pct".to_string(),
                    label: "区间涨幅最小值(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(15.0)),
                    description: None,
                    min: Some(-100.0),
                    max: Some(200.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "total_rise_max_pct".to_string(),
                    label: "区间涨幅最大值(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(5000.0)),
                    description: None,
                    min: Some(-100.0),
                    max: Some(5000.0),
                    options: None,
                },
            ],
        },
        StrategyTemplateDto {
            template: "daily_rise_turnover".to_string(),
            label: "连续上涨且换手率达标策略".to_string(),
            description: "过去N天每天涨幅>=阈值，且每天换手率>=阈值".to_string(),
            params: vec![
                StrategyTemplateParam {
                    key: "lookback_days".to_string(),
                    label: "回看天数".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(5)),
                    description: None,
                    min: Some(1.0),
                    max: Some(120.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "min_daily_rise_pct".to_string(),
                    label: "最小日涨幅(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(3.0)),
                    description: None,
                    min: Some(-100.0),
                    max: Some(200.0),
                    options: None,
                },
                StrategyTemplateParam {
                    key: "min_turnover_rate".to_string(),
                    label: "最小换手率(%)".to_string(),
                    r#type: "number".to_string(),
                    required: true,
                    default_value: Some(serde_json::json!(10.0)),
                    description: None,
                    min: Some(0.0),
                    max: Some(100.0),
                    options: None,
                },
            ],
        },
        StrategyTemplateDto {
            template: "ma_divergence_volume".to_string(),
            label: "均线向上发散放量策略".to_string(),
            description: "日均线向上发散，K线站上5日线(3-4天)，成交量连续放量>=2天".to_string(),
            params: vec![StrategyTemplateParam {
                key: "preset".to_string(),
                label: "预设".to_string(),
                r#type: "string".to_string(),
                required: false,
                default_value: Some(serde_json::json!("standard")),
                description: None,
                min: None,
                max: None,
                options: Some(vec![
                    serde_json::json!("standard"),
                    serde_json::json!("aggressive"),
                    serde_json::json!("conservative"),
                ]),
            }],
        },
        StrategyTemplateDto {
            template: "low_shadow".to_string(),
            label: "低位下影线策略".to_string(),
            description: "识别低位长下影线的反转信号".to_string(),
            params: vec![StrategyTemplateParam {
                key: "preset".to_string(),
                label: "预设".to_string(),
                r#type: "string".to_string(),
                required: false,
                default_value: Some(serde_json::json!("standard")),
                description: None,
                min: None,
                max: None,
                options: Some(vec![
                    serde_json::json!("standard"),
                    serde_json::json!("conservative"),
                    serde_json::json!("aggressive"),
                ]),
            }],
        },
        StrategyTemplateDto {
            template: "ma_convergence".to_string(),
            label: "均线粘合策略".to_string(),
            description: "识别均线粘合形态，筛选下跌后的粘合机会".to_string(),
            params: vec![StrategyTemplateParam {
                key: "preset".to_string(),
                label: "预设".to_string(),
                r#type: "string".to_string(),
                required: false,
                default_value: Some(serde_json::json!("daily_standard")),
                description: None,
                min: None,
                max: None,
                options: Some(vec![
                    serde_json::json!("daily_standard"),
                    serde_json::json!("daily_conservative"),
                    serde_json::json!("daily_aggressive"),
                    serde_json::json!("weekly_standard"),
                ]),
            }],
        },
        StrategyTemplateDto {
            template: "consecutive_bullish".to_string(),
            label: "日/周/月连阳策略".to_string(),
            description: "识别连续阳线形态，捕捉上升趋势的持续信号".to_string(),
            params: vec![StrategyTemplateParam {
                key: "preset".to_string(),
                label: "预设".to_string(),
                r#type: "string".to_string(),
                required: false,
                default_value: Some(serde_json::json!("daily_standard")),
                description: None,
                min: None,
                max: None,
                options: Some(vec![
                    serde_json::json!("daily_standard"),
                    serde_json::json!("daily_aggressive"),
                    serde_json::json!("weekly_standard"),
                    serde_json::json!("monthly_standard"),
                ]),
            }],
        },
    ];

    WebResponse::new(templates).into_result()
}
