//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use tushare_api::DeriveFromTushareData;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "block_trade"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, DeriveFromTushareData)]
pub struct Model {
    pub ts_code: String,
    pub trade_date: String,
    pub price: Option<Decimal>,
    pub vol: Option<Decimal>,
    pub amount: Option<Decimal>,
    pub buyer: Option<String>,
    pub seller: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    TsCode,
    TradeDate,
    Price,
    Vol,
    Amount,
    Buyer,
    Seller,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TsCode,
    TradeDate,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TsCode => ColumnType::String(StringLen::N(20u32)).def(),
            Self::TradeDate => ColumnType::String(StringLen::N(20u32)).def(),
            Self::Price => ColumnType::Decimal(Some((10u32, 2u32))).def().null(),
            Self::Vol => ColumnType::Decimal(Some((10u32, 4u32))).def().null(),
            Self::Amount => ColumnType::Decimal(Some((10u32, 2u32))).def().null(),
            Self::Buyer => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Seller => ColumnType::String(StringLen::N(100u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
