//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "cn_security_info"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub secucode: String,
    pub security_code: String,
    pub security_name_abbr: String,
    pub security_type: Option<String>,
    pub security_type_code: Option<String>,
    pub org_code: Option<String>,
    pub org_name: String,
    pub org_name_en: Option<String>,
    pub formername: Option<String>,
    pub str_codea: Option<String>,
    pub str_namea: Option<String>,
    pub str_codeb: Option<String>,
    pub str_nameb: Option<String>,
    pub str_codeh: Option<String>,
    pub str_nameh: Option<String>,
    pub em2016: Option<String>,
    pub trade_market: Option<String>,
    pub trade_markett: Option<String>,
    pub trade_market_code: Option<String>,
    pub industrycsrc1: Option<String>,
    pub board_name_level: Option<String>,
    pub currency: Option<String>,
    pub president: Option<String>,
    pub legal_person: Option<String>,
    pub secretary: Option<String>,
    pub chairman: Option<String>,
    pub secpresent: Option<String>,
    pub indedirectors: Option<String>,
    pub org_tel: Option<String>,
    pub org_email: Option<String>,
    pub org_fax: Option<String>,
    pub org_web: Option<String>,
    pub address: Option<String>,
    pub reg_address: Option<String>,
    pub province: Option<String>,
    pub address_postcode: Option<String>,
    pub reg_capital: Option<Decimal>,
    pub reg_num: Option<String>,
    pub emp_num: Option<i32>,
    pub tatolnumber: Option<i32>,
    pub law_firm: Option<String>,
    pub accountfirm_name: Option<String>,
    pub org_profile: Option<String>,
    pub business_scope: Option<String>,
    pub main_business: Option<String>,
    pub listing_date: Option<String>,
    pub found_date: Option<String>,
    pub marketing_start_date: Option<String>,
    pub expand_name_abbrn: Option<String>,
    pub expand_name_pinyin: Option<String>,
    pub expand_name_abbr: Option<String>,
    pub host_broker: Option<String>,
    pub transfer_way: Option<String>,
    pub actual_holder: Option<String>,
    pub market_maker: Option<String>,
    pub trade_market_type: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub concepts: Option<String>
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    Secucode,
    SecurityCode,
    SecurityNameAbbr,
    SecurityType,
    SecurityTypeCode,
    OrgCode,
    OrgName,
    OrgNameEn,
    Formername,
    StrCodea,
    StrNamea,
    StrCodeb,
    StrNameb,
    StrCodeh,
    StrNameh,
    Em2016,
    TradeMarket,
    TradeMarkett,
    TradeMarketCode,
    Industrycsrc1,
    BoardNameLevel,
    Currency,
    President,
    LegalPerson,
    Secretary,
    Chairman,
    Secpresent,
    Indedirectors,
    OrgTel,
    OrgEmail,
    OrgFax,
    OrgWeb,
    Address,
    RegAddress,
    Province,
    AddressPostcode,
    RegCapital,
    RegNum,
    EmpNum,
    Tatolnumber,
    LawFirm,
    AccountfirmName,
    OrgProfile,
    BusinessScope,
    MainBusiness,
    ListingDate,
    FoundDate,
    MarketingStartDate,
    ExpandNameAbbrn,
    ExpandNamePinyin,
    ExpandNameAbbr,
    HostBroker,
    TransferWay,
    ActualHolder,
    MarketMaker,
    TradeMarketType,
    CreatedAt,
    UpdatedAt,
    Concepts,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Secucode,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Secucode => ColumnType::String(StringLen::N(20u32)).def(),
            Self::SecurityCode => ColumnType::String(StringLen::N(10u32)).def(),
            Self::SecurityNameAbbr => ColumnType::String(StringLen::N(50u32)).def(),
            Self::SecurityType => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::SecurityTypeCode => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::OrgCode => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::OrgName => ColumnType::String(StringLen::N(200u32)).def(),
            Self::OrgNameEn => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::Formername => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::StrCodea => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::StrNamea => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::StrCodeb => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::StrNameb => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::StrCodeh => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::StrNameh => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::Em2016 => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::TradeMarket => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::TradeMarkett => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::TradeMarketCode => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::Industrycsrc1 => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::BoardNameLevel => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Currency => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::President => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::LegalPerson => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Secretary => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Chairman => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Secpresent => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Indedirectors => ColumnType::Text.def().null(),
            Self::OrgTel => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::OrgEmail => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::OrgFax => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::OrgWeb => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::Address => ColumnType::Text.def().null(),
            Self::RegAddress => ColumnType::Text.def().null(),
            Self::Province => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::AddressPostcode => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::RegCapital => ColumnType::Decimal(Some((20u32, 4u32))).def().null(),
            Self::RegNum => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::EmpNum => ColumnType::Integer.def().null(),
            Self::Tatolnumber => ColumnType::Integer.def().null(),
            Self::LawFirm => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::AccountfirmName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::OrgProfile => ColumnType::Text.def().null(),
            Self::BusinessScope => ColumnType::Text.def().null(),
            Self::MainBusiness => ColumnType::Text.def().null(),
            Self::ListingDate => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::FoundDate => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::MarketingStartDate => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::ExpandNameAbbrn => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::ExpandNamePinyin => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::ExpandNameAbbr => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::HostBroker => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::TransferWay => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::ActualHolder => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::MarketMaker => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::TradeMarketType => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::CreatedAt => ColumnType::Timestamp.def().null(),
            Self::UpdatedAt => ColumnType::Timestamp.def().null(),
            Column::Concepts => ColumnType::Text.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
