//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use tushare_api::DeriveFromTushareData;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "dc_index"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, DeriveFromTushareData)]
pub struct Model {
    pub ts_code: String,
    pub trade_date: String,
    pub name: Option<String>,
    pub leading: Option<String>,
    pub leading_code: Option<String>,
    pub pct_change: Option<Decimal>,
    pub leading_pct: Option<Decimal>,
    pub total_mv: Option<Decimal>,
    pub turnover_rate: Option<Decimal>,
    pub up_num: Option<i32>,
    pub down_num: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    TsCode,
    TradeDate,
    Name,
    Leading,
    LeadingCode,
    PctChange,
    LeadingPct,
    TotalMv,
    TurnoverRate,
    UpNum,
    DownNum,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TsCode,
    TradeDate,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TsCode => ColumnType::String(StringLen::N(20u32)).def(),
            Self::TradeDate => ColumnType::String(StringLen::N(20u32)).def(),
            Self::Name => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Leading => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::LeadingCode => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::PctChange => ColumnType::Decimal(None).def().null(),
            Self::LeadingPct => ColumnType::Decimal(None).def().null(),
            Self::TotalMv => ColumnType::Decimal(None).def().null(),
            Self::TurnoverRate => ColumnType::Decimal(None).def().null(),
            Self::UpNum => ColumnType::Integer.def().null(),
            Self::DownNum => ColumnType::Integer.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
