//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use tushare_api::DeriveFromTushareData;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "etf"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, DeriveFromTushareData)]
pub struct Model {
    pub ts_code: String,
    pub csname: String,
    pub cname: Option<String>,
    pub extname: Option<String>,
    pub index_code: Option<String>,
    pub index_name: Option<String>,
    pub setup_date: Option<String>,
    pub list_date: Option<String>,
    pub list_status: Option<String>,
    pub exchange: Option<String>,
    pub custod_name: Option<String>,
    pub mgr_name: Option<String>,
    pub mgt_fee: Option<String>,
    pub etf_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    TsCode,
    Csname,
    Cname,
    Extname,
    IndexCode,
    IndexName,
    SetupDate,
    ListDate,
    ListStatus,
    Exchange,
    CustodName,
    MgrName,
    MgtFee,
    EtfType,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TsCode,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TsCode => ColumnType::String(StringLen::N(200u32)).def(),
            Self::Csname => ColumnType::String(StringLen::N(200u32)).def(),
            Self::Cname => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::Extname => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::IndexCode => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::IndexName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::SetupDate => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::ListDate => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::ListStatus => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::Exchange => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::CustodName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::MgrName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::MgtFee => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::EtfType => ColumnType::String(StringLen::N(200u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
