//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use tushare_api::DeriveFromTushareData;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "fund_portfolio"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, DeriveFromTushareData)]
pub struct Model {
    pub ts_code: String,
    pub ann_date: String,
    pub end_date: String,
    pub symbol: String,
    pub mkv: Decimal,
    pub amount: Decimal,
    pub stk_mkv_ratio: Option<Decimal>,
    pub stk_float_ratio: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    TsCode,
    AnnDate,
    EndDate,
    Symbol,
    Mkv,
    Amount,
    StkMkvRatio,
    StkFloatRatio,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TsCode,
    Symbol,
    AnnDate,
    EndDate,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String, String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TsCode => ColumnType::String(StringLen::N(45u32)).def(),
            Self::AnnDate => ColumnType::String(StringLen::N(45u32)).def(),
            Self::EndDate => ColumnType::String(StringLen::N(45u32)).def(),
            Self::Symbol => ColumnType::String(StringLen::N(45u32)).def(),
            Self::Mkv => ColumnType::Decimal(Some((10u32, 0u32))).def(),
            Self::Amount => ColumnType::Decimal(Some((10u32, 0u32))).def(),
            Self::StkMkvRatio => ColumnType::Decimal(Some((10u32, 0u32))).def().null(),
            Self::StkFloatRatio => ColumnType::Decimal(Some((10u32, 0u32))).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
