//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use tushare_api::DeriveFromTushareData;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "hm_detail"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, DeriveFromTushareData)]
pub struct Model {
    pub trade_date: Date,
    pub ts_code: String,
    pub ts_name: String,
    pub buy_amount: Decimal,
    pub sell_amount: Decimal,
    pub net_amount: Decimal,
    pub hm_name: String,
    pub hm_orgs: Option<String>,
    pub tag: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    TradeDate,
    TsCode,
    TsName,
    BuyAmount,
    SellAmount,
    NetAmount,
    HmName,
    HmOrgs,
    Tag,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TsCode,
    HmName,
    TradeDate,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String, Date);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TradeDate => ColumnType::Date.def(),
            Self::TsCode => ColumnType::String(StringLen::N(20u32)).def(),
            Self::TsName => ColumnType::String(StringLen::N(50u32)).def(),
            Self::BuyAmount => ColumnType::Decimal(Some((15u32, 2u32))).def(),
            Self::SellAmount => ColumnType::Decimal(Some((15u32, 2u32))).def(),
            Self::NetAmount => ColumnType::Decimal(Some((15u32, 2u32))).def(),
            Self::HmName => ColumnType::String(StringLen::N(100u32)).def(),
            Self::HmOrgs => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::Tag => ColumnType::String(StringLen::N(100u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
