//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "index_daily_basic"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub ts_code: String,
    pub trade_date: String,
    pub total_mv: Option<Decimal>,
    pub float_mv: Option<Decimal>,
    pub total_share: Option<Decimal>,
    pub float_share: Option<Decimal>,
    pub free_share: Option<Decimal>,
    pub turnover_rate: Option<Decimal>,
    pub turnover_rate_f: Option<Decimal>,
    pub pe: Option<Decimal>,
    pub pe_ttm: Option<Decimal>,
    pub pb: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    TsCode,
    TradeDate,
    TotalMv,
    FloatMv,
    TotalShare,
    FloatShare,
    FreeShare,
    TurnoverRate,
    TurnoverRateF,
    Pe,
    PeTtm,
    Pb,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TsCode,
    TradeDate,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TsCode => ColumnType::String(StringLen::N(10u32)).def(),
            Self::TradeDate => ColumnType::String(StringLen::N(10u32)).def(),
            Self::TotalMv => ColumnType::Decimal(None).def().null(),
            Self::FloatMv => ColumnType::Decimal(None).def().null(),
            Self::TotalShare => ColumnType::Decimal(None).def().null(),
            Self::FloatShare => ColumnType::Decimal(None).def().null(),
            Self::FreeShare => ColumnType::Decimal(None).def().null(),
            Self::TurnoverRate => ColumnType::Decimal(None).def().null(),
            Self::TurnoverRateF => ColumnType::Decimal(None).def().null(),
            Self::Pe => ColumnType::Decimal(None).def().null(),
            Self::PeTtm => ColumnType::Decimal(None).def().null(),
            Self::Pb => ColumnType::Decimal(None).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
