//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use tushare_api::DeriveFromTushareData;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "limit_list_d"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, DeriveFromTushareData)]
pub struct Model {
    pub trade_date: String,
    pub ts_code: String,
    pub industry: Option<String>,
    pub name: Option<String>,
    pub close: Option<Decimal>,
    pub pct_chg: Option<Decimal>,
    pub amount: Option<Decimal>,
    pub limit_amount: Option<Decimal>,
    pub float_mv: Option<Decimal>,
    pub total_mv: Option<Decimal>,
    pub turnover_ratio: Option<Decimal>,
    pub fd_amount: Option<Decimal>,
    pub first_time: Option<String>,
    pub last_time: Option<String>,
    pub open_times: Option<i32>,
    pub up_stat: Option<String>,
    pub limit_times: Option<i32>,
    pub limit: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    TradeDate,
    TsCode,
    Industry,
    Name,
    Close,
    PctChg,
    Amount,
    LimitAmount,
    FloatMv,
    TotalMv,
    TurnoverRatio,
    FdAmount,
    FirstTime,
    LastTime,
    OpenTimes,
    UpStat,
    LimitTimes,
    Limit,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TradeDate,
    TsCode,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TradeDate => ColumnType::String(StringLen::N(8u32)).def(),
            Self::TsCode => ColumnType::String(StringLen::N(10u32)).def(),
            Self::Industry => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::Name => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::Close => ColumnType::Decimal(Some((10u32, 2u32))).def().null(),
            Self::PctChg => ColumnType::Decimal(Some((6u32, 2u32))).def().null(),
            Self::Amount => ColumnType::Decimal(Some((15u32, 2u32))).def().null(),
            Self::LimitAmount => ColumnType::Decimal(Some((15u32, 2u32))).def().null(),
            Self::FloatMv => ColumnType::Decimal(Some((15u32, 2u32))).def().null(),
            Self::TotalMv => ColumnType::Decimal(Some((15u32, 2u32))).def().null(),
            Self::TurnoverRatio => ColumnType::Decimal(Some((8u32, 2u32))).def().null(),
            Self::FdAmount => ColumnType::Decimal(Some((15u32, 2u32))).def().null(),
            Self::FirstTime => ColumnType::String(StringLen::N(6u32)).def().null(),
            Self::LastTime => ColumnType::String(StringLen::N(6u32)).def().null(),
            Self::OpenTimes => ColumnType::Integer.def().null(),
            Self::UpStat => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::LimitTimes => ColumnType::Integer.def().null(),
            Self::Limit => ColumnType::String(StringLen::N(1u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
