//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use tushare_api::DeriveFromTushareData;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "margin"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, DeriveFromTushareData)]
pub struct Model {
    pub trade_date: String,
    pub exchange_id: String,
    pub rzye: Option<Decimal>,
    pub rzmre: Option<Decimal>,
    pub rzche: Option<Decimal>,
    pub rqye: Option<Decimal>,
    pub rqmcl: Option<Decimal>,
    pub rzrqye: Option<Decimal>,
    pub rqyl: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    TradeDate,
    ExchangeId,
    Rzye,
    Rzmre,
    Rzche,
    Rqye,
    Rqmcl,
    Rzrqye,
    Rqyl,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TradeDate,
    ExchangeId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TradeDate => ColumnType::String(StringLen::N(20u32)).def(),
            Self::ExchangeId => ColumnType::String(StringLen::N(10u32)).def(),
            Self::Rzye => ColumnType::Decimal(None).def().null(),
            Self::Rzmre => ColumnType::Decimal(None).def().null(),
            Self::Rzche => ColumnType::Decimal(None).def().null(),
            Self::Rqye => ColumnType::Decimal(None).def().null(),
            Self::Rqmcl => ColumnType::Decimal(None).def().null(),
            Self::Rzrqye => ColumnType::Decimal(None).def().null(),
            Self::Rqyl => ColumnType::Decimal(None).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
