//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "stock"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub ts_code: String,
    pub symbol: String,
    pub name: Option<String>,
    pub area: Option<String>,
    pub industry: Option<String>,
    pub fullname: Option<String>,
    pub enname: Option<String>,
    pub cnspell: Option<String>,
    pub market: Option<String>,
    pub exchange: Option<String>,
    pub curr_type: Option<String>,
    pub list_status: Option<String>,
    pub list_date: Option<String>,
    pub delist_date: Option<String>,
    pub is_hs: Option<String>,
    pub act_name: Option<String>,
    pub act_ent_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    TsCode,
    Symbol,
    Name,
    Area,
    Industry,
    Fullname,
    Enname,
    Cnspell,
    Market,
    Exchange,
    CurrType,
    ListStatus,
    ListDate,
    DelistDate,
    IsHs,
    ActName,
    ActEntType,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    TsCode,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::TsCode => ColumnType::String(StringLen::N(10u32)).def(),
            Self::Symbol => ColumnType::String(StringLen::N(10u32)).def(),
            Self::Name => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Area => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Industry => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Fullname => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Enname => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::Cnspell => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::Market => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::Exchange => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::CurrType => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::ListStatus => ColumnType::String(StringLen::N(5u32)).def().null(),
            Self::ListDate => ColumnType::String(StringLen::N(15u32)).def().null(),
            Self::DelistDate => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::IsHs => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::ActName => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::ActEntType => ColumnType::String(StringLen::N(20u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
