//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "us_company_info"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub web_address: Option<String>,
    pub local_name: Option<String>,
    pub local_name_language_code: Option<String>,
    pub short_name: Option<String>,
    pub business_country: Option<String>,
    pub domicile_country: Option<String>,
    pub place_of_incorporation: Option<String>,
    pub year_established: Option<i32>,
    pub industry_name: Option<String>,
    pub industry_group_name: Option<String>,
    pub sector_name: Option<String>,
    pub report_style_name: Option<String>,
    pub industry_template_name: Option<String>,
    pub country: Option<String>,
    pub symbol: String,
    pub exchange_id: String,
    pub business_description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    WebAddress,
    LocalName,
    LocalNameLanguageCode,
    ShortName,
    BusinessCountry,
    DomicileCountry,
    PlaceOfIncorporation,
    YearEstablished,
    IndustryName,
    IndustryGroupName,
    SectorName,
    ReportStyleName,
    IndustryTemplateName,
    Country,
    Symbol,
    ExchangeId,
    BusinessDescription,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ExchangeId,
    Symbol,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    UsStock,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::WebAddress => ColumnType::String(StringLen::N(500u32)).def().null(),
            Self::LocalName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::LocalNameLanguageCode => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::ShortName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::BusinessCountry => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::DomicileCountry => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::PlaceOfIncorporation => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::YearEstablished => ColumnType::Integer.def().null(),
            Self::IndustryName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::IndustryGroupName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::SectorName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::ReportStyleName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::IndustryTemplateName => ColumnType::String(StringLen::N(200u32)).def().null(),
            Self::Country => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::Symbol => ColumnType::String(StringLen::N(30u32)).def(),
            Self::ExchangeId => ColumnType::String(StringLen::N(10u32)).def(),
            Self::BusinessDescription => ColumnType::Text.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::UsStock => Entity::belongs_to(super::us_stock::Entity)
                .from((Column::ExchangeId, Column::Symbol))
                .to((super::us_stock::Column::ExchangeId, super::us_stock::Column::Symbol))
                .into(),
        }
    }
}

impl Related<super::us_stock::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsStock.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
