//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "us_main_indicator"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub symbol: String,
    pub secucode: String,
    pub exchange_id: String,
    pub total_market_cap: Option<Decimal>,
    pub currency: Option<String>,
    pub pe_ttm: Option<Decimal>,
    pub sale_gpr: Option<Decimal>,
    pub pb: Option<Decimal>,
    pub dividend_rate: Option<Decimal>,
    pub std_report_date: Option<String>,
    pub report_date: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    Symbol,
    Secucode,
    ExchangeId,
    TotalMarketCap,
    Currency,
    PeTtm,
    SaleGpr,
    Pb,
    DividendRate,
    StdReportDate,
    ReportDate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ExchangeId,
    Symbol,
    ReportDate,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Symbol => ColumnType::String(StringLen::N(20u32)).def(),
            Self::Secucode => ColumnType::String(StringLen::N(20u32)).def(),
            Self::ExchangeId => ColumnType::String(StringLen::N(20u32)).def(),
            Self::TotalMarketCap => ColumnType::Decimal(Some((20u32, 4u32))).def().null(),
            Self::Currency => ColumnType::String(StringLen::N(10u32)).def().null(),
            Self::PeTtm => ColumnType::Decimal(Some((10u32, 2u32))).def().null(),
            Self::SaleGpr => ColumnType::Decimal(Some((5u32, 2u32))).def().null(),
            Self::Pb => ColumnType::Decimal(Some((10u32, 2u32))).def().null(),
            Self::DividendRate => ColumnType::Decimal(Some((5u32, 2u32))).def().null(),
            Self::StdReportDate => ColumnType::String(StringLen::N(20u32)).def().null(),
            Self::ReportDate => ColumnType::String(StringLen::N(20u32)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
