//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "us_stock"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub symbol: String,
    pub exchange_id: String,
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn, PartialEq)]
pub enum Column {
    Symbol,
    ExchangeId,
    Name,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ExchangeId,
    Symbol,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    UsCompanyInfo,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Symbol => ColumnType::String(StringLen::N(10u32)).def(),
            Self::ExchangeId => ColumnType::String(StringLen::N(10u32)).def(),
            Self::Name => ColumnType::String(StringLen::N(80u32)).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::UsCompanyInfo => Entity::belongs_to(super::us_company_info::Entity)
                .from((Column::ExchangeId, Column::Symbol))
                .to((super::us_company_info::Column::ExchangeId, super::us_company_info::Column::Symbol))
                .into(),
        }
    }
}

impl Related<super::us_company_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsCompanyInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
